### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by ai** [jantimon/postcss-inline#1]
What is a difference between this plugin and postcss-url or postcss-assets?

**Comment by jantimon** [comment]
It does only inlining.
It allows you to filter which files should be inlined e.g. if you want to inline only .woff files:
`postcss([ require('postcss-inline')({filter: /.woff$/}) ])`
It allows you to remove files after inlining e.g. if you use it in combination with postcss-assets-rebase

**Comment by MoOx** [comment]
Why don't you just make a PR to add filter option to postcss-url?

**Comment by jantimon** [comment]
@MoOx trying to do that right now however postcss-url has a disgusting code-style - all semicolons are missing! ;)

**Comment by MoOx** [comment]
What are they for?

**Comment by jantimon** [comment]
Well much of it is taste - I am used to the community code style - You know the way node, v8, react, jquery, angular, backbone and almost every other important framework / library has been written in for the last 15 years.
Now only because coffeescript failed some people try to change the whole community code style..

For me its because of my internal pattern recognition - and the speed of reading and understanding statements.

```
return getCustomProcessor(fallback);
```

vs

```
return getCustomProcessor(fallback)
        (result, from, dirname, oldUrl, to, options, decl);
```

If I know the code style enforces semicolons I can stop reading after the semicolon ;)

Now the same thing without semicolons

```
return getCustomProcessor(fallback)
```

```
return getCustomProcessor(fallback)
        (result, from, dirname, oldUrl, to, options, decl)
```

The missing semicolons forces me to read the following line as well to be sure.
That makes reading through code without semicolons slower.

**Comment by jantimon** [comment]
@ai @MoOx as requested I created a pull request in order to unpublish postcss-inline.
Please let me know if this meets your expectations:
https://github.com/postcss/postcss-url/issues/61
